<?php

namespace Tests\Feature\Api;

use App\Enums\AssetCondition;
use App\Models\Location;
use App\Models\MutationLog;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\Concerns\InteractsWithAssetFixtures;
use Tests\TestCase;

/**
 * Tahap 5.4 §19, §33 — `PUT|PATCH /api/assets/{asset}`.
 */
class AssetUpdateTest extends TestCase
{
    use InteractsWithAssetFixtures;
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        Sanctum::actingAs($this->operator());
    }

    public function test_normal_update_changes_descriptive_fields(): void
    {
        $asset = $this->existingAsset('001', overrides: ['brand_model' => 'Old', 'condition' => AssetCondition::Baik]);

        $this->patchJson("/api/assets/{$asset->id}", [
            'brand_model' => 'New Brand',
            'serial_no' => 'SN-123',
            'condition' => 'kurang_baik',
        ])
            ->assertOk()
            ->assertJsonPath('data.brand_model', 'New Brand')
            ->assertJsonPath('data.serial_no', 'SN-123')
            ->assertJsonPath('data.condition', 'kurang_baik');
    }

    public function test_update_never_changes_sequence_or_asset_code(): void
    {
        $asset = $this->existingAsset('017', year: 2021);
        $originalCode = $asset->asset_code;

        $this->patchJson("/api/assets/{$asset->id}", ['brand_model' => 'x'])
            ->assertOk()
            ->assertJsonPath('data.sequence_no', '017')
            ->assertJsonPath('data.asset_code', $originalCode);

        $this->assertSame('017', $asset->fresh()->sequence_no);
    }

    public function test_client_cannot_set_sequence_no_or_asset_code_on_update(): void
    {
        $asset = $this->existingAsset('001');

        $this->patchJson("/api/assets/{$asset->id}", ['sequence_no' => '999'])
            ->assertStatus(422)->assertJsonValidationErrors('sequence_no');

        $this->patchJson("/api/assets/{$asset->id}", ['asset_code' => 'X.Y.Z.1.2000'])
            ->assertStatus(422)->assertJsonValidationErrors('asset_code');
    }

    public function test_written_off_fields_are_rejected_on_update(): void
    {
        $asset = $this->existingAsset('001');

        $this->patchJson("/api/assets/{$asset->id}", ['is_written_off' => true])
            ->assertStatus(422)->assertJsonValidationErrors('is_written_off');
    }

    public function test_quantity_other_than_one_is_rejected(): void
    {
        $asset = $this->existingAsset('001');

        $this->patchJson("/api/assets/{$asset->id}", ['quantity' => 2])
            ->assertStatus(422)->assertJsonValidationErrors('quantity');
    }

    public function test_moving_to_an_inactive_master_is_rejected(): void
    {
        $asset = $this->existingAsset('001');
        Location::query()->firstOrCreate(['code' => 'ZX'], ['name' => 'Nonaktif', 'is_active' => false]);

        $this->patchJson("/api/assets/{$asset->id}", ['location_code' => 'ZX'])
            ->assertStatus(422)->assertJsonValidationErrors('location_code');
    }

    public function test_invalid_category_subcategory_combination_is_rejected(): void
    {
        $asset = $this->existingAsset('001', loc: 'ZL', cat: 'ZC', sub: '001');
        $this->scope('ZL', 'ZD', '888');

        $this->patchJson("/api/assets/{$asset->id}", [
            'category_code' => 'ZD',
            'subcategory_code' => '001',
        ])
            ->assertStatus(422)->assertJsonValidationErrors('subcategory_code');
    }

    public function test_room_from_another_location_is_rejected(): void
    {
        $asset = $this->existingAsset('001', loc: 'ZL');
        $foreignRoom = $this->room('ZM');

        $this->patchJson("/api/assets/{$asset->id}", ['room_id' => $foreignRoom->id])
            ->assertStatus(422)->assertJsonValidationErrors('room_id');
    }

    public function test_changing_category_and_subcategory_updates_the_generated_asset_code(): void
    {
        $asset = $this->existingAsset('003', year: 2022, loc: 'ZL', cat: 'ZC', sub: '001');
        $this->scope('ZL', 'ZD', '004');

        // no location/room change -> no mutation log, but asset_code is regenerated by the DB
        $this->patchJson("/api/assets/{$asset->id}", [
            'category_code' => 'ZD',
            'subcategory_code' => '004',
        ])
            ->assertOk()
            ->assertJsonPath('data.sequence_no', '003')
            ->assertJsonPath('data.asset_code', 'ZL.ZD.004.003.2022');

        $this->assertDatabaseCount('mutation_logs', 0);
    }

    public function test_no_mutation_log_when_neither_location_nor_room_changes(): void
    {
        $room = $this->room('ZL');
        $asset = $this->existingAsset('001', overrides: ['room_id' => $room->id]);

        $this->patchJson("/api/assets/{$asset->id}", [
            'brand_model' => 'changed',
            'condition' => 'rusak_berat',
        ])->assertOk();

        $this->assertSame(0, MutationLog::query()->where('asset_id', $asset->id)->count());
    }

    public function test_partial_update_keeps_untouched_fields(): void
    {
        $asset = $this->existingAsset('001', overrides: [
            'brand_model' => 'Keep Me',
            'material' => 'BESI',
        ]);

        $this->patchJson("/api/assets/{$asset->id}", ['serial_no' => 'only-this'])
            ->assertOk()
            ->assertJsonPath('data.brand_model', 'Keep Me')
            ->assertJsonPath('data.material', 'BESI')
            ->assertJsonPath('data.serial_no', 'only-this');
    }
}
